- name: Create Consul Config Directory (as root)
  ansible.builtin.file:
    path: "{{ consul_config_dir }}"
    state: directory
    mode: '0755'

- name: Create Consul Working Directory (as user)
  ansible.builtin.file:
    path: "{{ consul_working_dir }}"
    owner: "{{ ansible_user }}"
    group: "staff"
    state: directory
    mode: '0755'
