- name: Ensure the HashiCorp Homebrew tap is present
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: Ensure Consul is installed from HashiCorp tap
  community.general.homebrew:
    name:
      - hashicorp/tap/consul
    state: latest
    update_homebrew: true
  register: consul_package_install

- name: Register if Consul was installed or updated
  ansible.builtin.set_fact:
    consul_package_updated: "{{ consul_package_install.changed }}"