---
nomad_plugin_dir: "{{ nomad_working_dir }}/plugins"

nomad_podman_driver_version: "0.6.4"
nomad_podman_driver_name: "nomad-driver-podman"

nomad_container_driver_version: "0.2.0-dev-0ba806e"
nomad_container_driver_name: "nomad-driver-container"
nomad_container_driver_repo: "https://github.com/anultravioletaurora/nomad-driver-container"
nomad_container_driver_archive: "nomad-driver-container-darwin-arm64.tar.gz"

nomad_container_driver_url: "{{ nomad_container_driver_repo }}/releases/download/v{{ nomad_container_driver_version }}/{{ nomad_container_driver_archive }}"
