---
minecraft_job_name: "minecraft-server"

minecraft_job_file_dest: "{{ nomad_jobs_dir }}/minecraft-server.nomad.hcl"

minecraft_server_executable: "{{ homebrew_dir }}/bin/minecraft-server"

minecraft_server_port: 25565
minecraft_rcon_port: 25575
minecraft_bedrock_port: 19132

minecraft_server_cpu: 2
minecraft_server_memory: 1024
