- name: Set datacenter fact for Nomad
  ansible.builtin.set_fact:
    datacenter: "{{ group_names | reject('equalto', 'all') | reject('equalto', 'ungrouped') | first }}"

- name: Debug datacenter fact
  ansible.builtin.debug:
    msg: "Datacenter set to {{ datacenter }}"