- name: Install JRE
  community.general.homebrew_cask:
    name: temurin
    state: present

- name: Install Minecraft Server  
  community.general.homebrew_cask:
    name: minecraft-server
    state: present

- name: Create Nomad job file for Minecraft server
  ansible.builtin.template:
    src: templates/minecraft-server.nomad.hcl.j2
    dest: "{{ job_file_dest }}"
    mode: '0644'

- name: Register Minecraft Server Nomad Job
  ansible.builtin.command:
    argv:
      - "{{ homebrew_dir }}/bin/nomad"
      - job
      - run
      - "{{ job_file_dest }}"