- name: Template Nomad server configuration
  ansible.builtin.template:
    src: templates/nomad.d/server.hcl.j2
    dest: "{{ nomad_config_dir }}/server.hcl"
    mode: '0644'
    owner: root
    group: wheel
