---
- name: Create tmp directory for Container driver plugin
  ansible.builtin.file:
    path: "/tmp/{{ nomad_container_driver_name }}"
    state: directory

- name: Create plugins directory for Nomad
  ansible.builtin.file:
    path: "/opt/nomad/plugins"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "staff"

- name: Download Container driver plugin
  ansible.builtin.get_url:
    url: "{{ nomad_container_driver_url }}"
    dest: "/tmp/{{ nomad_container_driver_name }}/nomad-driver-container-darwin-arm64.tar.gz"
    mode: '0644'

- name: Extract Container driver plugin
  ansible.builtin.command:
    argv:
      - /usr/bin/tar
      - xzf
      - "/tmp/{{ nomad_container_driver_name }}/nomad-driver-container-darwin-arm64.tar.gz"
      - -C
      - "/tmp/{{ nomad_container_driver_name }}"
    creates: "/tmp/{{ nomad_container_driver_name }}/nomad-driver-container"


- name: Move Container driver plugin to Nomad plugins directory
  ansible.builtin.copy:
    src: "/tmp/{{ nomad_container_driver_name }}/nomad-driver-container"
    dest: "/opt/nomad/plugins/{{ nomad_container_driver_name }}"
    remote_src: true
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "staff"
