- name: Create Nomad Config Directory (as root)
  become: true
  ansible.builtin.file:
    path: "{{ nomad_config_dir }}"
    state: directory
    mode: '0755'

- name: Create Nomad Working Directory (as user)
  ansible.builtin.file:
    path: "{{ nomad_working_dir }}"
    state: directory
    mode: '0755'

- name: Create Consul Config Directory (as root)
  become: true
  ansible.builtin.file:
    path: "{{ consul_config_dir }}"
    state: directory
    mode: '0755'

- name: Create Consul Working Directory (as user)
  ansible.builtin.file:
    path: "{{ consul_working_dir }}"
    state: directory
    mode: '0755'