---
- name: Ensure Nomad is installed from HashiCorp tap
  community.general.homebrew:
    name:
      - hashicorp/tap/nomad
    state: latest
    update_homebrew: true
  register: nomad_package_install

- name: Register if Nomad was installed or updated
  ansible.builtin.set_fact:
    nomad_package_updated: "{{ nomad_package_install.changed }}"

- name: Notify if Nomad was installed or updated
  ansible.builtin.debug:
    msg: "Nomad was {{ 'installed' if nomad_package_install.changed else 'already up to date' }}."

- name: Send Webhook notification if Nomad was installed or updated
  ansible.builtin.import_tasks: tasks/notify.yml
  vars:
    webhook_message: "Nomad was {{ 'installed' if nomad_package_install.changed else 'already up to date' }} on node {{ inventory_hostname }}."
  when: nomad_package_install.changed
