- name: Ensure Nomad is installed from HashiCorp tap
  community.general.homebrew:
    name:
      - hashicorp/tap/nomad
    state: latest
    update_homebrew: true
  register: nomad_package_install

- name: Register if Nomad was installed or updated
  ansible.builtin.set_fact:
    nomad_package_updated: "{{ nomad_package_install.changed }}"