- name: Create Directories for Nomad
  become: true
  ansible.builtin.import_tasks: directories.yml

- name: Install / Upgrade Nomad
  ansible.builtin.import_tasks: install.yml

- name: Download Container driver plugin
  ansible.builtin.import_tasks: container_driver.yml
  when: container.enabled | default(false)

- name: Download Podman driver plugin
  ansible.builtin.import_tasks: podman_driver.yml
  when: podman.enabled | default(false)

- name: Apply Nomad configuration templates
  become: true
  ansible.builtin.import_tasks: configuration.yml

- name: Apply LaunchAgents configuration
  ansible.builtin.import_tasks: launchagent.yml

- name: Kickstart Nomad services
  ansible.builtin.import_tasks: start.yml
  when: nomad_package_updated | default(false)
