- name: Create Directories for Nomad
  ansible.builtin.import_tasks: directories.yml

- name: Install / Upgrade Nomad and Consul
  ansible.builtin.import_tasks: install.yml

- name: Apply Nomad configuration templates
  ansible.builtin.import_tasks: templating.yml
