---
- name: Deploy Nomad Jobs
  hosts: all
  # Need to fetch IPv4 addresses for Consul's configuration
  gather_facts: true
  tasks:
    - name: Set additional facts
      ansible.builtin.include_role:
        name: set_facts
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Include GH Actions Role
      ansible.builtin.include_role:
        name: github_actions
      when: gh_actions.enabled | default(false) and ansible_facts['os_family'] == 'Darwin'

    - name: Include Minecraft Server Role
      ansible.builtin.include_role:
        name: minecraft
      when: minecraft.enabled | default(false) and ansible_facts['os_family'] == 'Darwin'

    - name: Include Zitadel Role
      ansible.builtin.include_role:
        name: zitadel
      when: zitadel.enabled | default(false) and ansible_facts['os_family'] == 'Darwin'
