- name: Perform Nomadintosh deployment
  hosts: all
  # Need to fetch IPv4 addresses for Consul's configuration
  gather_facts: true 
  tasks:
    - name: Include Podman role
      ansible.builtin.include_role:
        name: ./roles/podman
      when: podman | default(false)

    - name: Include Consul role
      ansible.builtin.include_role:
        name: ./roles/consul

    - name: Include Nomad role
      ansible.builtin.include_role:
        name: ./roles/nomad
