---
- name: Perform Nomadintosh deployment
  hosts: all
  # Need to fetch IPv4 addresses for Consul's configuration
  gather_facts: true
  pre_tasks:
    - name: Ensure host is running macOS
      ansible.builtin.assert:
        that: ansible_facts['os_family'] == 'Darwin'
        fail_msg: "This playbook is intended to run on macOS hosts only."

    - name: Set additional facts
      ansible.builtin.include_role:
        name: set_facts

    - name: Perform Software Update
      ansible.builtin.include_role:
        name: software_update
  tasks:
    - name: Install Homebrew
      ansible.builtin.include_role:
        name: geerlingguy.mac.homebrew
      vars:
        homebrew_taps:
          - name: hashicorp/tap
        homebrew_install_packages: "{{ additional_homebrew_packages | default([]) }}"

    - name: Include Container role
      ansible.builtin.include_role:
        name: container
      when: container.enabled | default(false)

    - name: Include Docker Desktop role
      ansible.builtin.include_role:
        name: docker_desktop
      when: docker.enabled | default(false)

    - name: Include Podman role
      ansible.builtin.include_role:
        name: podman
      when: podman.enabled | default(false)

    - name: Include Consul role
      ansible.builtin.include_role:
        name: consul

    - name: Include Nomad role
      ansible.builtin.include_role:
        name: nomad

    - name: Deploy Nomad Jobs
      ansible.builtin.import_playbook: jobs.yml
